version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"       # MQTT TCP
      - "9001:9001"       # MQTT WebSocket
    volumes:
      - ./cloud/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./cloud/mosquitto.passwd:/mosquitto/config/mosquitto.passwd:ro

  simulator:
    build:
      context: ./simulator
    container_name: iot-edge-simulator
    depends_on:
      - mosquitto
    environment:
      MQTT_BROKER_URL: ${MQTT_BROKER_URL}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT}
      MQTT_TOPIC: ${MQTT_TOPIC}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}

  dashboard:
    build:
      context: ./react-dashboard
    container_name: react-dashboard
    depends_on:
      - mosquitto
    ports:
      - "3000:80"   # Expose dashboard on localhost:3000